"""Traefik file-mode dynamic config writer.

One YAML file per pod, written into the shared dynamic dir. Traefik watches
the dir and reloads on change. We never edit the static traefik.yml.

Spec ref: spec/07-c4.md §"Traefik". Replaces v1's port-counter logic.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

log = logging.getLogger("mcp-pods.traefik")


def _sanitise_router(pod_id: str) -> str:
    """Traefik names allow [a-zA-Z0-9-]; coerce."""
    return re.sub(r"[^a-zA-Z0-9-]", "-", pod_id).strip("-") or "pod"


def write_rule(*, dynamic_dir: Path, pod_id: str, display_role: str, service_port: int) -> Path:
    """Write a Traefik dynamic rule for a pod's HTTP service.

    Hostname: `<display_role>.conclave.local`. Backend resolves to the
    pod's main container by container DNS (`<pod_id>:port`).
    """
    rid = _sanitise_router(pod_id)
    role = _sanitise_router(display_role)
    path = dynamic_dir / f"pod-{rid}.yml"
    contents = f"""# Auto-generated by mcp-pods. Edit at your own risk.
http:
  routers:
    {rid}:
      rule: "Host(`{role}.conclave.local`)"
      entryPoints: [web]
      service: {rid}-svc
  services:
    {rid}-svc:
      loadBalancer:
        servers:
          - url: "http://{pod_id}:{service_port}"
"""
    path.write_text(contents)
    log.info("wrote traefik rule %s for %s @ %s.conclave.local",
             path, pod_id, role)
    return path


def remove_rule(*, dynamic_dir: Path, pod_id: str) -> bool:
    rid = _sanitise_router(pod_id)
    path = dynamic_dir / f"pod-{rid}.yml"
    if path.exists():
        path.unlink()
        log.info("removed traefik rule %s", path)
        return True
    return False
