"""Jinja2 renderers for wizard outputs: compose, pod workflow, env file.

All templates use StrictUndefined so missing variables fail loudly.
"""

from __future__ import annotations

import jinja2

from ..adapters.ci.github_actions import _DEFAULT_TEMPLATE as _POD_WORKFLOW_TEMPLATE
from ..core.config import ConclaveConfig, TraceSlot

_env = jinja2.Environment(autoescape=False, undefined=jinja2.StrictUndefined)  # noqa: S701

# Bind-mount the local platform source into every service so the alpha doesn't
# need a published image. Pragmatic trade-off: slower first start, no registry.
# MCP services are placeholders until those servers ship.
_PLATFORM_IMAGE = "python:3.12-slim"
_PLATFORM_INSTALL = "pip install --quiet uv && uv pip install --system ."

_PYTHON_SERVICES: tuple[tuple[str, str, int, str, list[str]], ...] = (
    ("observer", "conclave-observer", 8000, "Bus only", ["bus"]),
    ("senate-ledger", "conclave-senate", 8001, "Bus only", ["bus"]),
    ("mcp-coms", "conclave-mcp-coms", 8002, "Bus only", ["bus"]),
    ("mcp-senate", "conclave-mcp-senate", 8003, "Senate", ["bus", "senate-ledger"]),
    ("mcp-decisions", "conclave-mcp-decisions", 8004, "Bus only", ["bus"]),
    ("mcp-state", "conclave-mcp-state", 8005, "Bus only", ["bus"]),
)


_COMPOSE_TEMPLATE = """\
# Generated by conclave-wizard. Pods are added lazily by the runtime adapter.
name: conclave

services:
  bus:
    image: nats:2.10-alpine
    container_name: conclave-bus
    ports:
      - "4222:4222"
    networks:
      - conclave
    restart: unless-stopped
{% for svc, command, port, env_kind, depends in python_services %}
  # TODO: enable once the {{ svc }} server ships (placeholder image).
  {{ svc }}:
    image: {{ platform_image }}
    container_name: conclave-{{ svc }}
    working_dir: /platform
    command:
      - sh
      - -c
      - "{{ platform_install }} && {{ command }}"
    ports:
      - "{{ port }}:{{ port }}"
    volumes:
      - ./platform:/platform:ro
    environment:
      BUS_URL: nats://bus:4222
{%- if env_kind == "Senate" %}
      SENATE_URL: http://senate-ledger:8001
{%- endif %}
    depends_on:
{%- for d in depends %}
      - {{ d }}
{%- endfor %}
    networks:
      - conclave
    restart: unless-stopped
{% endfor %}
{%- if include_tempo %}
  tempo:
    image: grafana/tempo:latest
    container_name: conclave-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
      - "4317:4317"
    networks:
      - conclave
    restart: unless-stopped
{%- endif %}

networks:
  conclave:
    driver: bridge
"""


def render_compose(config: ConclaveConfig) -> str:
    tmpl = _env.from_string(_COMPOSE_TEMPLATE)
    return tmpl.render(
        include_tempo=config.slots.trace == TraceSlot.otel_tempo,
        platform_image=_PLATFORM_IMAGE,
        platform_install=_PLATFORM_INSTALL,
        python_services=_PYTHON_SERVICES,
    )


def render_pod_workflow(pod_name: str) -> str:
    tmpl = _env.from_string(_POD_WORKFLOW_TEMPLATE)
    return tmpl.render(pod=pod_name)


_ENV_TEMPLATE = """\
# Generated by conclave-wizard. Do not commit.
GITHUB_TOKEN={{ github_token }}
{% if telegram_bot_token -%}
TELEGRAM_BOT_TOKEN={{ telegram_bot_token }}
{% endif -%}
{% if telegram_chat_id -%}
TELEGRAM_CHAT_ID={{ telegram_chat_id }}
{% endif -%}
"""


def render_env(
    config: ConclaveConfig,
    *,
    github_token: str,
    telegram_bot_token: str | None,
    telegram_chat_id: str | None,
) -> str:
    del config  # presently unused; kept for future slot-aware credentials
    tmpl = _env.from_string(_ENV_TEMPLATE)
    return tmpl.render(
        github_token=github_token,
        telegram_bot_token=telegram_bot_token,
        telegram_chat_id=telegram_chat_id,
    )
